
server:
  port: 8002
spring:
  application:
    name: guli-oss
  profiles:
    active: dev

aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: f
      keysecret: f
      bucketname: guli-c1eye
      filehost: avatar


