
server:
  port: 8002
spring:
  application:
    name: guli-oss
  profiles:
    active: dev

aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5t77r4pqMiru98K89HjN
      keysecret: kSHOx33IHa0C12XWeCkRWZz3NHIHUK
      bucketname: guli-c1eye
      filehost: avatar


