# 服务端口
#server.port=8001
#  # 服务名
#spring.application.name=guli-teacher
#  # 环境设置：dev、test、prod
#spring.profiles.active=dev
#  # mysql数据库连接
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/guli_edu?characterEncoding=utf-8&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=mysql
#  #mybatis日志
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8001

spring:
  application:
    name: guli-teacher
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_edu?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: mmj_MMJ_123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/guli/teacher/mapper/xml/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8004/eureka/
  instance:
    prefer-ip-address: true
