server:
  port: 8003

spring:
  profiles:
    active: dev
  application:
    name: guli-vod
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB



  #阿里云 vod
  #不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid: LTAI5t77r4pqMiru98K89HjN
      keysecret: kSHOx33IHa0C12XWeCkRWZz3NHIHUK
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8004/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connect-timeout: 2000
        read-timeout: 6000
